apiVersion: apps/v1 # for versions before 1.6.0 use extensions/v1beta1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:v0.16.1
        ports:
        - containerPort: 9093
        args:
        - --config.file=/etc/monitoring/alertmanager.yml
        volumeMounts:
        - name: alerting-config
          mountPath: /etc/monitoring
      volumes:
      - name: alerting-config
        configMap:
          name: alerting-config
