---
# Source: prometheus-pushgateway/templates/serviceaccount.yaml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: test-prometheus-pushgateway
  labels:
    app: prometheus-pushgateway
    # chart: prometheus-pushgateway-1.4.1
    # heritage: Helm
    # release: test
---
# Source: prometheus-pushgateway/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: test-prometheus-pushgateway
  annotations:
    {}
  labels:
    app: prometheus-pushgateway
    # chart: prometheus-pushgateway-1.4.1
    # heritage: Helm
    # release: test
spec:
  type: NodePort
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: prometheus-pushgateway
    # release: test
