---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-prometheus-pushgateway
  labels:
    app: prometheus-pushgateway
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: prometheus-pushgateway
  template:
    metadata:
      annotations:
        prometheus.io/path: "/metrics"
        prometheus.io/port: '9091'
        prometheus.io/scrape: 'true'
      labels:
        app: prometheus-pushgateway
    spec:
      serviceAccountName: test-prometheus-pushgateway
      containers:
        - name: pushgateway
          image: "prom/pushgateway:v1.2.0"
          imagePullPolicy: IfNotPresent
          ports:
            - name: metrics
              containerPort: 9091
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /-/healthy
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /-/ready
              port: 9091
            initialDelaySeconds: 10
            timeoutSeconds: 10
