---
apiVersion: v1
kind: Service
metadata:
  name: test-prometheus-pushgateway
  labels:
    app: prometheus-pushgateway
spec:
  type: LoadBalancer
  ports:
    - port: 9091
      targetPort: 9091
      protocol: TCP
      name: http
  selector:
    app: prometheus-pushgateway
